services:
  api:
    build:
      context: .
      dockerfile: build/package/Dockerfile
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: photolib
      POSTGRES_HOST: db
  db:
    image: "postgres"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: photolib
    volumes:
      - ./build/package/table.sql:/docker-entrypoint-initdb.d/init.sql
